import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/layout/navigation";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.variable}  antialiased`}>
        <div className="w-full">
          <div className="container px-5 md:px-6 mx-auto">
            <Navigation />
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
